uiless-dev:
  # use `shift-f9` to toggle the hud.
  MTL_HUD_ENABLED=1 cargo run -- --uiless

uiless-run:
  MTL_HUD_ENABLED=1 cargo run --release -- --uiless

ui-dev:
  MTL_HUD_ENABLED=1 cargo run

ui-run:
  MTL_HUD_ENABLED=1 cargo run --release